"""add_phone_num

Revision ID: 670dc9c95cf2
Revises: a30111b5cbb3
Create Date: 2023-07-06 23:31:39.525802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670dc9c95cf2'
down_revision = 'a30111b5cbb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
